bookyourdoctor/Models/PatientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace bookyourdoctor.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    namespace bookyourdoctor.Models
    {
        public class ExternalLoginConfirmationViewModel
        {
            [Required]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }

        public class ExternalLoginListViewModel
        {
            public string ReturnUrl { get; set; }
        }

        public class SendCodeViewModel
        {
            public string SelectedProvider { get; set; }
            public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
            public string ReturnUrl { get; set; }
            public bool RememberMe { get; set; }
        }

        public class VerifyCodeViewModel
        {
            [Required]
            public string Provider { get; set; }

            [Required]
            [Display(Name = "Code")]
            public string Code { get; set; }
            public string ReturnUrl { get; set; }

            [Display(Name = "Remember this browser?")]
            public bool RememberBrowser { get; set; }

            public bool RememberMe { get; set; }
        }

        public class ForgotViewModel
        {
            [Required]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }

        public class LoginViewModel
        {
            [Required]
            [Display(Name = "Email")]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public class RegisterViewModel
        {
           
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            [StringLength(100, ErrorMessage = "The {0} must be at least {6} characters long.", MinimumLength = 6)]

            public string Name;
            public int PhoneNumber;
           


        }

        public class ResetPasswordViewModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }

            public string Code { get; set; }
        }

        public class ForgotPasswordViewModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }
        }
    }

}

bookyourdoctor/Models/patient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public string name { get; set; }
        public string email { get; set; }
        public string contact_number { get; set; }
        public string password { get; set; }
    }
}

bookyourdoctor/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bookyourdoctor.Controllers
{
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        // GET: Patient/Details/5
        

        // GET: Patient/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult SelectDoctor()
        {
            return View();
        }

        public ActionResult ViewDoctorDetails()
        {
            return View();
        }
        public ActionResult TakeAppoitment()
        {
            return View();
        }

        public ActionResult CardiologistsDetails()
        {
            return View();
        }

        public ActionResult ChildSpecialistDetails()
        {
            return View();
        }

        public ActionResult DermatologistDetails()
        {
            return View();
        }
        public ActionResult GynecologistDetails()
        {
            return View();
        }

        public ActionResult DentistDetails()
        {
            return View();
        }
        public ActionResult PsychologistDetails()
        {
            return View();
        }
        // POST: Patient/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Patient/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Patient/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Patient/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Patient/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

bookyourdoctor/Controllers/patientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using bookyourdoctor;
using bookyourdoctor.Models;

namespace bookyourdoctor.Controllers
{
    public class patientsController : Controller
    {
        private bookdoctorEntities3 db = new bookdoctorEntities3();

        // GET: patients
        public ActionResult Index()
        {
            return View(db.patients.ToList());
        }

        // GET: patients/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: patients/Create
        public ActionResult Create()
        {
            return View();
        }



        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(patient p)
        {
            using (bookdoctorEntities3 db = new bookdoctorEntities3())
            {
                var usr = db.patients.SingleOrDefault(u => u.email == p.email);
                if (usr != null)
                {
                    if(usr.password.ToString() == p.password.ToString())
                    {
                        Session["email"] = usr.email.ToString();
                        return RedirectToAction("SelectDoctor");

                    }
                }
                else
                {
                    ModelState.AddModelError("", "Email or password is wrong");
                }
            }
            return View(p);

        }

        

        public ActionResult SelectDoctor()
        {
            return View();
        }

        public ActionResult ViewDoctorDetails()
        {
            return View();
        }
        public ActionResult TakeAppoitment()
        {
            return View();
        }

        public ActionResult CardiologistsDetails()
        {
            return View();
        }

        public ActionResult ChildSpecialistDetails()
        {
            return View();
        }

        public ActionResult DermatologistDetails()
        {
            return View();
        }
        public ActionResult GynecologistDetails()
        {
            return View();
        }

        public ActionResult DentistDetails()
        {
            return View();
        }
        public ActionResult PsychologistDetails()
        {
            return View();
        }

        // POST: patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "name,email,contact_number,password")] patient patient)
        {
            if (ModelState.IsValid)
            {
                db.patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("SelectDoctor");
            }

            return View(patient);
        }

        // GET: patients/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "name,email,contact_number,password")] patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: patients/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            patient patient = db.patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            patient patient = db.patients.Find(id);
            db.patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

bookyourdoctor/Views/patients/Create.cshtml
@model bookyourdoctor.patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contact_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contact_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

bookyourdoctor/Views/patients/Delete.cshtml
@model bookyourdoctor.patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contact_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contact_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

bookyourdoctor/Views/patients/Details.cshtml
@model bookyourdoctor.patient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contact_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contact_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.email }) |
    @Html.ActionLink("Back to List", "Index")
</p>

bookyourdoctor/Views/patients/Edit.cshtml
@model bookyourdoctor.patient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.email)

        <div class="form-group">
            @Html.LabelFor(model => model.contact_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contact_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

bookyourdoctor/Views/patients/Index.cshtml
@model IEnumerable<bookyourdoctor.patient>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contact_number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contact_number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.email }) |
            @Html.ActionLink("Details", "Details", new { id = item.email }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.email })
        </td>
    </tr>
}

</table>

bookyourdoctor/Views/patients/Login.cshtml
@model bookyourdoctor.patient

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

bookyourdoctor/Views/patients/SelectDoctor.cshtml
@{
    ViewBag.Title = "SelectDoctor";
}
<body style="background-image:url(../images/qqq.jpg);
  background-repeat: no-repeat;
  background-size: cover;
  height:400px;">
    <style>

        .square {
            height: 250px;
            width: 300px;
            background-color: white;
            position: relative;
            left: 50px;
            border-radius: 50%;
            top: 45px;
        }

        .square1 {
            height: 250px;
            width: 300px;
            background-color: white;
            position: relative;
            left: 500px;
            border-radius: 50%;
            bottom: 500px;
        }

        .square2 {
            height: 250px;
            width: 300px;
            background-color: white;
            position: relative;
            left: 950px;
            border-radius: 50%;
            bottom: 1030px;
        }
    </style>


    <div class="square" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Cardiologists", "CardiologistsDetails", "Patient")</h3>
        <p>
            Cardiology is a branch of medicine</br> dealing with disorders of the heart as</br> well as parts of the circulatory system.</br>
            The field includes medical diagnosis</br> and treatment of congenital heart defects.
        </p>
    </div>
    <div class="square" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Child Specialist", "ChildSpecialistDetails", "Patient")</h3>
        <p>
            Child life specialists are </br> pediatric health care professionals</br> who work with children to help</br>them cope with the challenges </br>of hospitalization, illness, and disability..
        </p>
    </div>
    <div class="square1" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Gynecologist", "GynecologistDetails", "Patient")</h3>
        <p>
            A gynecologist treats the</br>overall health of their female patients</br>treating problems and diseases of </br>the female reproductive system.</bf>A gynecologist is an obstetrician as</br> well.
        </p>
    </div>
    <div class="square1" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Dermatologist", "DermatologistDetails", "Patient")</h3>
        <p>
            A dermatologist is a doctor who</br> specializes in the study of skin </br> and the treatment of skin diseases.</br> A physician who specializes in the</br> diagnosis and treatment of skin problems.
        </p>
    </div>
    <div class="square2" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Dentist", "DentistDetails", "Patient")</h3>
        <p>
            One who is skilled in and licensed</br> to practice the prevention, diagnosis,</br> and treatment of diseases, injuries,</br> and malformations of the teeth, </br>jaws, and mouth and who makes and</br> inserts false teeth.

        </p>
    </div>
    <div class="square2" style="padding-left:30px">
        <h3 style="padding-left:55px; padding-top:30px">@Html.ActionLink("Psychologist", "PsychologistDetails", "Patient")</h3>
        <p>
            Clinical psychologists diagnose and</br> treat individuals suffering from</br> psychological distress and mental illness.</br> They also perform psychotherapy and</br> develop treatment plans.
        </p>
    </div>
</body>

bookyourdoctor/Views/patients/ViewDoctorDetails.cshtml
@model bookyourdoctor.doctor

@{
    ViewBag.Title = "ViewDoctorDetails";
}

<h2>ViewDoctorDetails</h2>